# Generated by Django 2.2 on 2019-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPWEB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='mail@mail.com', max_length=40),
        ),
    ]
