# Generated by Django 2.2 on 2019-05-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPWEB', '0002_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
